n = input('Digite algo: ')
#print('Só tem espaços?', n.isspace(), '\n', 'É um número?', n.isnumeric(), '\n', 'É um alfabeto?', n.isalpha(), '\n', 'É um alfanumérico?', n.isalnum(), '\n', 'Está em maiúscula?', n.isupper(), '\n', 'Está em minúsculas?', n.islower(), '\n', 'Está capitalizada?', n.istitle())
print('O tipo primitivo desse valor é:', type(n)) 
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabeto?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúsculas?', n.isupper())
print('Está em minusculas?', n.islower())
print('Está centralizada?', n.istitle())
